"""
Minimal static file server for Cloud Run / Railway / any container host.

Serves the contents of public/ on the PORT environment variable (default 8080).
Exposes endpoints:
  POST /run              - protected by X-Run-Token (for Cloud Scheduler)
  POST /run-now          - unauthenticated (for the UI "Run Now" button)
  POST /delete-run       - unauthenticated (for the UI "Delete" button)
  POST /analyze-quality  - unauthenticated (for the UI "Analyze Quality" button)
Pipeline triggers are guarded by a lock to prevent concurrent runs.
"""

from __future__ import annotations

import hmac
import json
import logging
import os
import shutil
import threading
from http.server import HTTPServer, SimpleHTTPRequestHandler
from pathlib import Path

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
log = logging.getLogger("server")

PORT = int(os.environ.get("PORT", "8080"))
PUBLIC_DIR = Path(__file__).parent / "public"
DATA_DIR = Path(__file__).parent / "data"
RUN_SECRET = os.environ.get("RUN_SECRET", "")

_run_lock = threading.Lock()

# ── Quality analysis prompt ──────────────────────────────────────────────────

_ANALYSIS_SYSTEM = """\
You are a senior editorial quality analyst and AI/tech industry expert. \
You have been asked to audit the output of an automated daily AI news digest \
called "AI Pulse." The digest is generated by a pipeline that ingests news \
from Exa, Hacker News, and Reddit, clusters and deduplicates them, then uses \
an LLM to curate and write executive briefs.

Your job is to provide a rigorous, constructive quality analysis. Be specific. \
Give concrete examples from the items you see. Do not be generic or polite - \
the operator needs actionable feedback.

Structure your response as markdown with these exact sections:

## Overall Grade
Give a letter grade (A through F) and a one-sentence summary.

## Relevance and Signal-to-Noise
Are these genuinely the most important AI/tech stories for the period? \
Flag any filler, low-impact, or "so what?" items that dilute the digest.

## Depth and Completeness
Do the executive briefs fully answer the 5Ws and 2Hs? Point out any items \
that are shallow, missing key context, or leave obvious questions unanswered.

## Writing Quality
Is the prose clear, authoritative, and free of filler? Are headlines punchy \
and accurate? Flag any cliches, vagueness, or marketing language.

## Source Diversity
Are items pulling from varied sources, or is there over-reliance on one type \
(e.g. all press releases, all from one outlet)?

## Coverage Gaps
Based on your knowledge, are there major AI/tech stories from this period \
that are missing entirely? List the top 3-5 stories that should have been \
included.

## Scoring Calibration
Are impact scores consistent and well-calibrated across items? Any scores \
that seem too high or too low relative to the actual story importance?

## Recommendations for Improvement
Provide 5-10 concrete, prioritized recommendations for improving the tool. \
These can be changes to: the ingestion sources, the clustering/dedup logic, \
the curation prompt, the rendering/UX, new skills or capabilities to add, \
or any other aspect of the pipeline. Be specific enough that a developer \
could implement each recommendation.\
"""


class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(PUBLIC_DIR), **kwargs)

    def do_POST(self):
        if self.path == "/run":
            token = self.headers.get("X-Run-Token", "")
            if not RUN_SECRET or not hmac.compare_digest(token, RUN_SECRET):
                self.send_error(403, "Forbidden - invalid or missing X-Run-Token")
                log.warning("Rejected /run request - bad token from %s", self.client_address[0])
                return
            self._start_pipeline()

        elif self.path == "/run-now":
            self._start_pipeline()

        elif self.path == "/delete-run":
            self._handle_delete_run()

        elif self.path == "/analyze-quality":
            self._handle_analyze_quality()

        else:
            self.send_error(404)

    def _start_pipeline(self):
        if not _run_lock.acquire(blocking=False):
            self.send_response(429)
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(b"A pipeline run is already in progress\n")
            return

        self.send_response(202)
        self.send_header("Content-Type", "text/plain")
        self.end_headers()
        self.wfile.write(b"Pipeline triggered\n")
        threading.Thread(target=self._run_pipeline, daemon=True).start()

    def _handle_delete_run(self):
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length) if content_length else b""
        try:
            data = json.loads(body) if body else {}
        except json.JSONDecodeError:
            self.send_error(400, "Invalid JSON")
            return

        run_id = data.get("run_id", "")
        if not run_id or "/" in run_id or ".." in run_id:
            self.send_error(400, "Invalid run_id")
            return

        run_dir = PUBLIC_DIR / "runs" / run_id
        if run_dir.exists():
            shutil.rmtree(run_dir)
            log.info("Deleted run directory: %s", run_dir)

        idx_path = DATA_DIR / "runs_index.json"
        if idx_path.exists():
            try:
                index = json.loads(idx_path.read_text(encoding="utf-8"))
                index = [r for r in index if r.get("run_id") != run_id]
                idx_path.write_text(json.dumps(index, indent=2, ensure_ascii=False), encoding="utf-8")
                log.info("Removed run %s from index (%d remaining)", run_id, len(index))
            except Exception as exc:
                log.error("Failed to update runs index: %s", exc)

        from src.render import render_homepage
        from src.state import load_runs_index
        render_homepage(load_runs_index())

        self.send_response(200)
        self.send_header("Content-Type", "text/plain")
        self.end_headers()
        self.wfile.write(b"Run deleted\n")

    def _handle_analyze_quality(self):
        """Load recent runs, send items to Claude for quality analysis."""
        from src.state import load_runs_index

        index = load_runs_index()
        if not index:
            self.send_response(400)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"error": "No runs to analyze"}).encode())
            return

        runs_to_analyze = index[:7]

        md_parts: list[str] = []
        total_items = 0
        for run_entry in runs_to_analyze:
            rid = run_entry.get("run_id", "")
            digest_path = PUBLIC_DIR / "runs" / rid / "digest.json"
            if not digest_path.exists():
                continue
            try:
                digest = json.loads(digest_path.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                continue

            ts = run_entry.get("timestamp", rid)
            md_parts.append(f"# Run: {ts}\n")
            for item in digest.get("items", []):
                total_items += 1
                headline = item.get("headline", "Untitled")
                summary = item.get("summary", "")
                brief = item.get("executive_brief", "")
                score = item.get("impact_score", "?")
                category = item.get("category", "?")
                links = item.get("links", [])
                link_labels = ", ".join(l.get("label", "?") for l in links) if links else "none"

                md_parts.append(
                    f"## {headline}\n"
                    f"**Impact Score:** {score} | **Category:** {category} | **Sources:** {link_labels}\n\n"
                    f"**Summary:** {summary}\n\n"
                    f"**Executive Brief:**\n{brief}\n\n---\n"
                )

        if total_items == 0:
            self.send_response(400)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"error": "No items found in runs"}).encode())
            return

        user_msg = (
            f"Below are {total_items} news items from the last {len(runs_to_analyze)} "
            f"runs of the AI Pulse digest. Analyze the quality of this output.\n\n"
            + "\n".join(md_parts)
        )

        log.info("Analyze quality: %d items from %d runs, prompt ~%d chars",
                 total_items, len(runs_to_analyze), len(user_msg))

        try:
            from src import config
            from openai import OpenAI

            client = OpenAI(
                base_url=config.OPENROUTER_BASE_URL,
                api_key=config.OPENROUTER_API_KEY,
            )
            response = client.chat.completions.create(
                model=config.CURATOR_MODEL,
                max_tokens=4096,
                messages=[
                    {"role": "system", "content": _ANALYSIS_SYSTEM},
                    {"role": "user", "content": user_msg},
                ],
                extra_headers={
                    "HTTP-Referer": "https://ai-pulse-daily.run.app",
                    "X-Title": "AI Pulse Quality Analysis",
                },
            )
            analysis = response.choices[0].message.content if response.choices else ""
            log.info("Quality analysis complete (%d chars)", len(analysis or ""))
        except Exception as exc:
            log.exception("Quality analysis LLM call failed")
            self.send_response(500)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps({"error": str(exc)}).encode())
            return

        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.end_headers()
        self.wfile.write(json.dumps({
            "analysis": analysis or "",
            "runs_analyzed": len(runs_to_analyze),
            "items_analyzed": total_items,
        }).encode())

    @staticmethod
    def _run_pipeline():
        try:
            from src.main import run
            run()
            log.info("Pipeline run completed")
        except Exception:
            log.exception("Pipeline run failed")
        finally:
            _run_lock.release()

    def log_message(self, format, *args):
        log.info(format, *args)


def main():
    PUBLIC_DIR.mkdir(parents=True, exist_ok=True)
    if not (PUBLIC_DIR / "index.html").exists():
        log.info("No index.html found - running initial pipeline")
        try:
            from src.main import run
            run()
        except Exception:
            log.exception("Initial pipeline failed; serving whatever is in public/")

    server = HTTPServer(("0.0.0.0", PORT), Handler)
    log.info("Serving %s on port %d", PUBLIC_DIR, PORT)
    server.serve_forever()


if __name__ == "__main__":
    main()
